# -*- coding: utf-8 -*-
"""Gender Face Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ltINdRfbej-16ovwEbcZrD_X4v7_1KQ
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

# Commented out IPython magic to ensure Python compatibility.
!mkdir {HOME}/datasets
# %cd {HOME}/datasets

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="rP1Kp5d7XKxPPJi6cudx")
project = rf.workspace("facegenderdetection").project("face-gender-recognition-cegug")
version = project.version(1)
dataset = version.download("yolov8")



# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

model = YOLO("yolov8n.pt")



model.train(task='detect',
            data='/content/datasets/Face-Gender-Recognition-1/data.yaml',
            epochs=10, imgsz=800,
            plots=True,
            mode='train')

"""**Confusion matrix**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/confusion_matrix.png', width=600)

"""**Result**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/results.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/val_batch0_pred.jpg', width=600)

"""**In dataset, man and woman are denoted as '1','0'**

**Florence Model**
"""

f = Roboflow(api_key="rP1Kp5d7XKxPPJi6cudx")
project = rf.workspace("facegenderdetection").project("face-gender-recognition-cegug")
version = project.version(1)
dataset = version.download("florence2-od")

